{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "face-recognition.serviceAccountName" . }}
  labels:
{{ include "face-recognition.labels" . | nindent 4 }}
{{- end -}}
