name: deploy

on:
  push
  # push:
  #   branches:
  #     - master

jobs:
  deploy:
    container: alpine/helm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir -p ~/.kube
      - run: echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
      - name: get image repository
        id: image-repository
        run: |
          TAG=${{ github.sha }}
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && TAG=$(echo $VERSION | sed -e 's/^v//')
          IMAGE_NAME=$(echo ${{ github.repository }} | sed -e 's/.*\///')
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME:$TAG
          echo "::set-output name=repository::$IMAGE_ID"
      - run: helm upgrade --install --namespace yoyota
          --set image.repository=${{ steps.image-repository.outputs.repository }}
          --set image.tag=${{ github.sha }}
          --set imagePullSecrets[0].name=regcred-github-com
          --history-max 2
          face-recognition ./helm
